//
// tilemap_format_gbdk_c_source.c
//

#include <stdio.h>
#include <string.h>

#include "lib_tilemap.h"
#include "tilemap_io.h"
#include "tilemap_path_ops.h"
#include "tilemap_format_gbdk_c_source.h"



// TODO: allow control of which bank they are written to
// TOOD: bank in filename is hardwired right now ("map.b3.c")
//
int32_t tilemap_format_gbdk_c_source_save(const char * filename, tile_map_data * tile_map, tile_set_data * tile_set) {

    int t,c;
    FILE * file;

    char path_without_filename[STR_FILENAME_MAX];

    char filename_tiles_c[STR_FILENAME_MAX];
    char filename_tiles_h[STR_FILENAME_MAX];
    char filename_map_c[STR_FILENAME_MAX];
    char filename_map_h[STR_FILENAME_MAX];

printf("Writing to gbdk C source files...\n");

    // TODO: resume honoring requested filename for output
/*
    snprintf(filename_tiles_c, STR_FILENAME_MAX, "%s.tiles.b3.c", filename);
    snprintf(filename_tiles_h, STR_FILENAME_MAX, "%s.tiles.h",    filename);

    snprintf(filename_map_c,   STR_FILENAME_MAX, "%s.map.b3.c", filename);
    snprintf(filename_map_h,   STR_FILENAME_MAX, "%s.map.h",    filename);
*/
    if (!get_path_without_filename(filename, path_without_filename, STR_FILENAME_MAX)) {
      return (false);
    }

    snprintf(filename_tiles_c, STR_FILENAME_MAX, "%stiles.b3.c", path_without_filename);
    snprintf(filename_tiles_h, STR_FILENAME_MAX, "%stiles.h",    path_without_filename);

    snprintf(filename_map_c,   STR_FILENAME_MAX, "%smap.b3.c", path_without_filename);
    snprintf(filename_map_h,   STR_FILENAME_MAX, "%smap.h",    path_without_filename);

    printf("%s\n", filename_tiles_c);
    printf("%s\n", filename_tiles_h);
    printf("%s\n", filename_map_c);
    printf("%s\n", filename_map_h);



printf("// ==== TILE SET C SOURCE FILE ====\n");
    // ==== TILE SET C SOURCE FILE ====

    // Open the file
    file = fopen(filename_tiles_c, "w");
    if(!file)
        return (false);

    //snprintf(str_header_info, STR_HEADER_MAX, "/*
    fprintf(file, "/*\n\nFilename: %s \n\
     \n\
     Tile Source File\n\
     \n\
     Info:\n\
      Form                 : All tiles as one unit\n\
      Format               : Gameboy 4 color\n\
      Compression          : None\n\
      Counter              : None\n\
      Tile size            : %d x %d\n\
      Tiles                : 0 to %d\n\
      \n\
      Palette colors       : None\n\
      SGB Palette          : None\n\
      CGB Palette          : None\n\
      \n\
      Convert to metatiles : No\n\
      \n\
      This file was generated by: Gimp Tilemap Plugin\n\
      \n\
    */\n\
      \n\
    /* Start of tile array */\n\
    const unsigned  char tiles[] =\n\
    {\n", get_filename_from_path(filename_tiles_c),
    tile_set->tile_width,
    tile_set->tile_height,
    tile_set->tile_count);

    // Write all the tile set data to a file
    for (t = 0; t < tile_set->tile_count; t++) {
        // Write the tile if it has data
        if (tile_set->tiles[t].p_img_encoded) {

            for (c = 0; c < tile_set->tiles[t].encoded_size_bytes; c++) {
                fprintf(file, " 0x%02x,", tile_set->tiles[t].p_img_encoded[c]);

                if (c && (((c+1) % 8) == 0))
                    fprintf(file, "\n"); // Periodic line break
            }
            fprintf(file, "\n"); // Line break between every tile
        }
    }

    // Close the array
    fprintf(file, " };\n");

    // Close the file
    fclose(file);


printf("// ==== TILE SET C HEADER FILE ====\n");
    // ==== TILE SET C HEADER FILE ====

    // Open the file
    file = fopen(filename_tiles_h, "w");
    if(!file)
        return (false);

    fprintf(file, "/*\n\nFilename: %s \n\
    \n\
    Tile Header File\n\
    */\n\
    \n\
    /* Bank of tiles */\n\
    #define tilesBank 0\n\
    \n\
    /* Start of tile array */\n\
    extern unsigned char tiles[];\n\
    \n",get_filename_from_path(filename_tiles_h));

    // Close the file
    fclose(file);



printf("// ==== TILE MAP C SOURCE FILE ====\n");
    // ==== TILE MAP C SOURCE FILE ====

    // Open the file
    file = fopen(filename_map_c, "w");
    if(!file)
        return (false);

    fprintf(file, "/*\n\nFilename: %s \n\
    \n\
    Map SOURCE File \n\
    \n\
     Info:\n\
       Section       :\n\
       Bank          : 0\n\
       Map size      : %d x %d \n\
       Tile set      : %s.gbr\n\
       Plane count   : 1 plane (8 bits)\n\
       Plane order   : Tiles are continues\n\
       Tile offset   : 0\n\
       Split data    : No\n\
    \n\
    This file was generated by: Gimp Tilemap Plugin\n\
    */\n\
    \n\
    #define mapWidth %d\n\
    #define mapHeight %d\n\
    #define mapBank 0\n\
    \n\
    const unsigned char map[]=\n\
    {\n",get_filename_from_path(filename_map_c),
        tile_map->width_in_tiles,
        tile_map->height_in_tiles,
        get_filename_from_path(filename_map_c),
        tile_map->width_in_tiles,
        tile_map->height_in_tiles);

    // Write all the Tile Map data to a file
    for (t = 0; t < tile_map->size; t++) {

        fprintf(file, " %3d,", tile_map->tile_id_list[t]);

        if (t && (((t+1) % 16) == 0))
            fprintf(file, "\n"); // Line break every 8 tiles

        if (t && (((t+1) % 64) == 0))
            fprintf(file, "\n"); // Bigger line break every 64 tiles
    }


    // Close the array
    fprintf(file, " };\n");

    // Close the file
    fclose(file);




printf("// ==== TILE MAP C HEADER FILE ====\n");
    // ==== TILE MAP C HEADER FILE ====

    // Open the file
    file = fopen(filename_map_h, "w");
    if(!file)
        return (false);

    fprintf(file, "/*\n\nFilename: %s \n\
    \n\
    Map Include File \n\
    \n\
     Info:\n\
       Section       :\n\
       Bank          : 0\n\
       Map size      : %d x %d\n\
       Tile set      : %s.gbr\n\
       Plane count   : 1 plane (8 bits)\n\
       Plane order   : Tiles are continues\n\
       Tile offset   : 0\n\
       Split data    : No\n\
    \n\
    This file was generated by: Gimp Tilemap Plugin\n\
    */\n\
    \n\
    #define mapWidth %d\n\
    #define mapHeight %d\n\
    #define mapBank 0\n\
    \n\
    extern unsigned char map[];\n\
    \n",get_filename_from_path(filename_map_c),
        tile_map->width_in_tiles,
        tile_map->height_in_tiles,
        get_filename_from_path(filename_map_c),
        tile_map->width_in_tiles,
        tile_map->height_in_tiles);

    // Close the file
    fclose(file);




    return (true);
}

